---
- name: Launch proxy container
  docker_container:
    name: http
    image: thomaspct/tp-devops-http:latest 
    pull: yes
    ports:
      - "80:80" 
      - "8080:8080"
    networks:
      - name: proxy_app_network